services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: shopflow/airflow:local
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      # Read FERNET key from env (.env file) so you can supply a valid key
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data_extraction:/opt/airflow/project/data_extraction
      - ./dbt_shopflow:/opt/airflow/project/dbt_shopflow
      - ./logs/airflow:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    command: bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true && airflow webserver"

  scheduler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: shopflow/airflow:local
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data_extraction:/opt/airflow/project/data_extraction
      - ./dbt_shopflow:/opt/airflow/project/dbt_shopflow
      - ./logs/airflow:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: airflow scheduler

volumes:
  postgres_db:
